<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title><?php echo $pagename ?></title>
    <link rel="stylesheet" type="text/css" href="../../../css/bootstrap.css">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-light bg-faded">
        <a class="navbar-brand" href="#">F1 2014 Season</a>
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="">Ranking</a>
            </li>
        </ul>
    </nav>
    <br>