<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title><?php echo $pagename ?></title>
    <link rel="stylesheet" type="text/css" href="../../../css/bootstrap.css">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-light bg-faded">
        <a class="navbar-brand" href="#">Suggestion Box</a>
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="http://suggestionboxmvc.local/meineVorschlaege">Meine Vorschläge</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://suggestionboxmvc.local/neuerVorschlag">Neuer Vorschlag</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://suggestionboxmvc.local/Rangliste">Rangliste</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://suggestionboxmvc.local/aktuelles">Aktuelles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://suggestionboxmvc.local/account">Account</a>
            </li>
        </ul>
    </nav>
    <br>