<?php
extract($data);
if ($i == 1) {
    echo '<h1>Rangliste</h1><br><br>
<div id="list">';
}

echo "<div class=\"row\" >
            <div class=\"col-sm-10 suggestion\" >
                <h2>. $title</h2>
                <p>$description</p>
                <span><strong>Eingereicht am: $date</strong></span><br>
                <span><strong>Von: $author</strong></span><br>
                <span name=\"votes$vid\"><strong>Stimme(n): $votes</strong></span>
            </div>";
if (array_search($vid, $votesgiven) !== false) {
    echo "<div class=\"col-sm-2\">
                    <button type=\"submit\" class=\"btn btn-warning votebutton\" name=\"downvotex$vid\" >downvote</button>
            </div>
        </div>";
} else {
    echo "<div class=\"col-sm-2\">
                    <button type=\"submit\" class=\"btn btn-success votebutton\" name=\"upvotex$vid\" >upvote</button>
            </div>
        </div>";
}

