<?php
/**
 * Created by PhpStorm.
 * User: Stephan Hauff
 * Date: 07.03.2016
 * Time: 14:21
 */
extract($data);
if($i == 1){
    echo "<h1>Meine Vorschläge</h1><br><br>";
}
echo "<div class=\"row\">
            <div class=\"col-sm-10\">
                <h2>. $title</h2>
                <p>$description</p>
                <span><strong>Eingereicht am: $date</span><br>
                <span>Stimme(n): $votes</span></strong></span>
            </div>
            <div class=\"col-sm-2\">
                <form onsubmit=\"return confirm('Vorschlag $title wirklich löschen?');\" method=\"POST\" action=\"http://suggestionboxmvc.local/meineVorschlaege/delete/$vid\">
                    <button type=\"submit\" class=\"btn btn-danger\" name=\"delete\">Vorschlag löschen</button>
                </form>
            </div>
            <hr />
        </div><br>";



