<?php
require 'views/header.phtml'; ?>

<h1>Login</h1><br><br>
<form action="http://suggestionboxmvc.local/account/login" method="post" class="col-sm-4">
    <fieldset class="form-group">
        <label for="name">Name:</label>
        <input type="text" class="form-control" size="40" maxlength="250" name="name">
    </fieldset>
    <fieldset class="form-group">
        <label for="password">Passwort:</label>
        <input type="password" class="form-control" size="40" maxlength="250" name="password">
    </fieldset>

    <input type="submit" class="btn btn-primary pull-sm-right" value="Login">
    <?php
    if (isset($_SESSION['login'])) {
        if ($_SESSION['login'] == false) {
            session_unset(); // clear the $_SESSION variable
            if (isset($_COOKIE[session_name()])) {
                setcookie(session_name(), '', time() - 3600); # Unset the session id
            }
            session_destroy();
            echo "<span>Login fehlgeschlagen!</span>";
        }
    }
    ?>
</form><br>


<?php require 'views/footer.phtml'; ?>



